### ISSUE TITLE
Java Script Dsa

### ISSUE THREAD

**Issue by Morbius00** [benedictprajwal/hacktoberfest-2022-algo-projects#37]
# Java Script DSA
>Want to add a java_Script Dsa tutorial folder 
Please assigned me for this.

**Comment by benedictprajwal** [comment]
sure

**Comment by Morbius00** [comment]
> sure

Please add the Hacktober fest label

**Comment by ARCHITABHATTAD** [comment]
@benedictprajwal I have some canvas JavaScript projects, can you please assign me this issue
